name: Semgrep CI

on:
  pull_request:
    paths:
      - 'Risk Assessment Case Study - OWASP Juice Shop/juice-shop/**'
      - '.github/workflows/semgrep.yml'
  push:
    branches:
      - main
      - master
    paths:
      - 'Risk Assessment Case Study - OWASP Juice Shop/juice-shop/**'
      - '.github/workflows/semgrep.yml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    defaults:
      run:
        working-directory: Risk_Assessment_Case_Study-OWASP_Juice_Shop/juice-shop

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep CI
        run: semgrep ci --debug
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}